### ISSUE TITLE
Anyone interested in merged output lots, and safe adjustments for whole-dollar rounding?

### ISSUE THREAD

**Issue by avinash311** [adlr/wash-sale-calculator#11]
Not sure if these options are something I should try to commit to this code - or the protocol for discussing that, so submitting this as an issue...

Along with some minor changes (changed titles of rows to make it easier for importing into TaxAct), I also have these options working locally:
  -m, --merge_split_lots
                        Any split lots are merged back together at end. This
                        makes it easier to match the output to the input lots,
                        but can cause the buy-dates to be slightly incorrect
                        since a lot can only have a single buy date. In this
                        mode, some wash sale lots may have a loss that is
                        greater than the adjustment amount, instead of being
                        identical, i.e., only part of the loss in the lot is
                        actually a wash sale. This is expected in this mode..
  -r, --adjust_for_dollar_rounding
                        Some tax software packages will round the basis,
                        proceeds and adjustment to calculate the total loss
                        (or profit). This can cause problems for wash sales
                        which instead of having a loss of $0 may now have a
                        profit of $1, which results in a warning about a wash
                        sale lot with a profit. Fix this by slightly modifying
                        the adjustment amount so that the final loss will be
                        $0 in such cases. It is safe to use this option with
                        the merge_split_lots option.

If there is interest, I can submit some or all of these changes.
Without the -r option, I get too many warnings in TaxAct during the Alerts phase.
And it has lots ending up with $1 profit or $1 loss, when it should have been all $0 for (unmerged) wash sale lots.

**Comment by mag1024** [comment]
FWIW, I'd definitely be in favour of -m. Currently do this in semi-manually in spreadsheets.

**Comment by avinash311** [comment]
While not ready for prime time, I've a fork with the code, but tests had to be simplified, so may need more work. It works fine for my purpose though :-)
https://github.com/avinash311/wash-sale-calculator

Closing this issue...

**Comment by avinash311** [comment]
It seems that merging is a good thing and may be necessary at least by my reading of the [IRS 8949 instructions](https://www.irs.gov/pub/irs-pdf/i8949.pdf) - copied from the first page:

>  Form 8949 allows you and the IRS to reconcile amounts that were reported to you and the IRS on Form 1099-B or 1099-S (or substitute statement) with the amounts you report on your return. If you receive Form 1099-B or 1099-S (or substitute statement), always report the proceeds (sales price) shown on that form (or statement) in column (d) of Form 8949. 

So, having the column d match each 1099-b (or each row of a consolidated 1099-b) might avoid any IRS follow related to how it was all computed.
